# Generated by Django 2.2.6 on 2022-09-19 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20220919_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(validators=[django.core.validators.RegexValidator(code='required', message='А кто поле будет заполнять? Пушкин?')]),
        ),
    ]
