# Generated by Django 2.2.6 on 2022-09-19 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20220919_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(validators=[django.core.validators.RegexValidator(code='required', message='А кто поле будет заполнять? Пушкин?', regex='<([a-zA-Z_0-9]*)>')]),
        ),
    ]
