# Generated by Django 2.2.6 on 2022-09-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20220919_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(error_messages={'required': 'А кто поле будет заполнять? Пушкин?'}),
        ),
    ]
